name: amparo_app
description: Aplicativo amparo
version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  cupertino_icons: ^1.0.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/certificates/
    - assets/fonts/
    - assets/images/logo.png
    - assets/images/frame.png
  fonts:
    - family: Archivo
      fonts:
        - asset: assets/fonts/Archivo-Light.ttf
    - family: SF Pro
      fonts:
        - asset: assets/fonts/SFProDisplay-Bold.ttf
    - family: Audiowide
      fonts:
        - asset: assets/fonts/Audiowide-Regular.ttf
    - family: SF Pro Medium
      fonts:
        - asset: assets/fonts/SFProDisplay-Medium.ttf