enum FederativeUnit {
  AC,
  AL,
  AP,
  AM,
  BA,
  CE,
  DF,
  ES,
  GO,
  MA,
  MT,
  MS,
  MG,
  PA,
  PB,
  PR,
  PE,
  PI,
  RJ,
  RN,
  RS,
  RO,
  RR,
  SC,
  SP,
  SE,
  TO
}

const Map<String, FederativeUnit> ResponseFederativeUnitMap = {
  'AC': FederativeUnit.AC,
  'AL': FederativeUnit.AL,
  'AP': FederativeUnit.AP,
  'AM': FederativeUnit.AM,
  'BA': FederativeUnit.BA,
  'CE': FederativeUnit.CE,
  'DF': FederativeUnit.DF,
  'ES': FederativeUnit.ES,
  'GO': FederativeUnit.GO,
  'MA': FederativeUnit.MA,
  'MT': FederativeUnit.MT,
  'MS': FederativeUnit.MS,
  'MG': FederativeUnit.MG,
  'PA': FederativeUnit.PA,
  'PB': FederativeUnit.PB,
  'PR': FederativeUnit.PR,
  'PE': FederativeUnit.PE,
  'PI': FederativeUnit.PI,
  'RJ': FederativeUnit.RJ,
  'RN': FederativeUnit.RN,
  'RS': FederativeUnit.RS,
  'RO': FederativeUnit.RO,
  'RR': FederativeUnit.RR,
  'SC': FederativeUnit.SC,
  'SP': FederativeUnit.SP,
  'SE': FederativeUnit.SE,
  'TO': FederativeUnit.TO
};

const Map<FederativeUnit, String> RequestFederativeUnitMap = {
  FederativeUnit.AC: 'AC',
  FederativeUnit.AL: 'AL',
  FederativeUnit.AP: 'AP',
  FederativeUnit.AM: 'AM',
  FederativeUnit.BA: 'BA',
  FederativeUnit.CE: 'CE',
  FederativeUnit.DF: 'DF',
  FederativeUnit.ES: 'ES',
  FederativeUnit.GO: 'GO',
  FederativeUnit.MA: 'MA',
  FederativeUnit.MT: 'MT',
  FederativeUnit.MS: 'MS',
  FederativeUnit.MG: 'MG',
  FederativeUnit.PA: 'PA',
  FederativeUnit.PB: 'PB',
  FederativeUnit.PR: 'PR',
  FederativeUnit.PE: 'PE',
  FederativeUnit.PI: 'PI',
  FederativeUnit.RJ: 'RJ',
  FederativeUnit.RN: 'RN',
  FederativeUnit.RS: 'RS',
  FederativeUnit.RO: 'RO',
  FederativeUnit.RR: 'RR',
  FederativeUnit.SC: 'SC',
  FederativeUnit.SP: 'SP',
  FederativeUnit.SE: 'SE',
  FederativeUnit.TO: 'TO'
};
